--------------------------------------------------------
--  File created - Tuesday-May-13-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_USERS
--------------------------------------------------------

  CREATE TABLE "ORACLE"."TBL_USERS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"USER_ID" NUMBER, 
	"USER_REGDATE" DATE, 
	"USER_LAST_LOGIN" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ADDRESS1" VARCHAR2(500 BYTE), 
	"ADDRESS2" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"POSTALCODE" NUMBER, 
	"Mobile " VARCHAR2(200 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORACLE.TBL_USERS
SET DEFINE OFF;
Insert into ORACLE.TBL_USERS (NAME,PASS,USER_ID,USER_REGDATE,USER_LAST_LOGIN,ADDRESS1,ADDRESS2,STATE,POSTALCODE,"Mobile ",FIRSTNAME,LASTNAME) values ('xyz','x123',61,to_date('10-MAY-14','DD-MON-RR'),to_timestamp('10-MAY-14 07.30.58.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'New York',null,'NY',12345,'0','XYZ','ABC');
Insert into ORACLE.TBL_USERS (NAME,PASS,USER_ID,USER_REGDATE,USER_LAST_LOGIN,ADDRESS1,ADDRESS2,STATE,POSTALCODE,"Mobile ",FIRSTNAME,LASTNAME) values ('purva','p123',41,to_date('10-MAY-14','DD-MON-RR'),to_timestamp('10-MAY-14 03.47.01.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'xyz, College Park',null,'MD',20740,'1234567890','Purva','M');
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."USERS_PK" ON "ORACLE"."TBL_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_USERS
--------------------------------------------------------

  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("POSTALCODE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("USER_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORACLE"."TBL_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger USERS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ORACLE"."USERS_TRIGGER" 
before insert on TBL_USERS
for each row
begin
select users_seq.nextval into:new.UID from USERS;
end;
/
ALTER TRIGGER "ORACLE"."USERS_TRIGGER" DISABLE;
