--------------------------------------------------------
--  File created - Tuesday-May-13-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ORDER_ITEM
--------------------------------------------------------

  CREATE TABLE "ORACLE"."TBL_ORDER_ITEM" 
   (	"OD_ID" NUMBER, 
	"PD_ID" NUMBER, 
	"OD_QTY" NUMBER, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORACLE.TBL_ORDER_ITEM
SET DEFINE OFF;
Insert into ORACLE.TBL_ORDER_ITEM (OD_ID,PD_ID,OD_QTY,USER_ID) values (3,1,1,41);
Insert into ORACLE.TBL_ORDER_ITEM (OD_ID,PD_ID,OD_QTY,USER_ID) values (1,21,1,41);
Insert into ORACLE.TBL_ORDER_ITEM (OD_ID,PD_ID,OD_QTY,USER_ID) values (1,22,1,41);
--------------------------------------------------------
--  DDL for Index TBL_ORDER_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."TBL_ORDER_ITEM_PK" ON "ORACLE"."TBL_ORDER_ITEM" ("PD_ID", "OD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" ADD CONSTRAINT "TBL_ORDER_ITEM_PK" PRIMARY KEY ("PD_ID", "OD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" MODIFY ("OD_QTY" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" MODIFY ("PD_ID" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" MODIFY ("OD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" ADD CONSTRAINT "TBL_ORDER_ITEM_TBL_ORDER_FK1" FOREIGN KEY ("OD_ID")
	  REFERENCES "ORACLE"."TBL_ORDER" ("OD_ID") ENABLE;
  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" ADD CONSTRAINT "TBL_ORDER_ITEM_TBL_PRODUC_FK1" FOREIGN KEY ("PD_ID")
	  REFERENCES "ORACLE"."TBL_PRODUCT" ("PD_ID") ENABLE;
  ALTER TABLE "ORACLE"."TBL_ORDER_ITEM" ADD CONSTRAINT "TBL_ORDER_ITEM_TBL_USERS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ORACLE"."TBL_USERS" ("USER_ID") ENABLE;
