--------------------------------------------------------
--  File created - Tuesday-May-13-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ORDER
--------------------------------------------------------

  CREATE TABLE "ORACLE"."TBL_ORDER" 
   (	"OD_ID" NUMBER, 
	"OD_DATE" DATE, 
	"OD_SHIPPING_FIRST_NAME" VARCHAR2(20 BYTE), 
	"OD_SHIPPING_LAST_NAME" VARCHAR2(20 BYTE), 
	"OD_SHIPPING_ADDRESS1" VARCHAR2(20 BYTE), 
	"OD_SHIPPING_ADDRESS2" VARCHAR2(20 BYTE), 
	"OD_SHIPPING_PHONE" NUMBER, 
	"OD_SHIPPING_STATE" VARCHAR2(20 BYTE), 
	"OD_SHIPPING_POSTAL_CODE" NUMBER, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORACLE.TBL_ORDER
SET DEFINE OFF;
Insert into ORACLE.TBL_ORDER (OD_ID,OD_DATE,OD_SHIPPING_FIRST_NAME,OD_SHIPPING_LAST_NAME,OD_SHIPPING_ADDRESS1,OD_SHIPPING_ADDRESS2,OD_SHIPPING_PHONE,OD_SHIPPING_STATE,OD_SHIPPING_POSTAL_CODE,USER_ID) values (3,to_date('10-MAY-14','DD-MON-RR'),'puy','buybuy','xyz, College Park','null',1234567890,'MD',20740,41);
Insert into ORACLE.TBL_ORDER (OD_ID,OD_DATE,OD_SHIPPING_FIRST_NAME,OD_SHIPPING_LAST_NAME,OD_SHIPPING_ADDRESS1,OD_SHIPPING_ADDRESS2,OD_SHIPPING_PHONE,OD_SHIPPING_STATE,OD_SHIPPING_POSTAL_CODE,USER_ID) values (2,to_date('10-MAY-14','DD-MON-RR'),'puy','buybuy','NY',null,1234567890,'NY',12345,41);
Insert into ORACLE.TBL_ORDER (OD_ID,OD_DATE,OD_SHIPPING_FIRST_NAME,OD_SHIPPING_LAST_NAME,OD_SHIPPING_ADDRESS1,OD_SHIPPING_ADDRESS2,OD_SHIPPING_PHONE,OD_SHIPPING_STATE,OD_SHIPPING_POSTAL_CODE,USER_ID) values (1,to_date('10-MAY-14','DD-MON-RR'),'puy','buybuy','xyz, College Park','null',1234567890,'MD',20740,41);
--------------------------------------------------------
--  DDL for Index TBL_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORACLE"."TBL_ORDER_PK" ON "ORACLE"."TBL_ORDER" ("OD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_ORDER
--------------------------------------------------------

  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" ADD CONSTRAINT "TBL_ORDER_PK" PRIMARY KEY ("OD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_SHIPPING_POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_SHIPPING_STATE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_SHIPPING_PHONE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_SHIPPING_ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_SHIPPING_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_DATE" NOT NULL ENABLE);
  ALTER TABLE "ORACLE"."TBL_ORDER" MODIFY ("OD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_ORDER
--------------------------------------------------------

  ALTER TABLE "ORACLE"."TBL_ORDER" ADD CONSTRAINT "TBL_ORDER_TBL_USERS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ORACLE"."TBL_USERS" ("USER_ID") ENABLE;
